### ISSUE TITLE
Peer to peer code review 2nd mdl wk 4

### ISSUE THREAD

**Issue by Bavon101** [daudi13/LeaderBoard#2]
Hello @daudi13 , 
Your project structure so far looks amazing and well structured, you can do these minor changes to improve the site:

- [ ] When displaying the array object, you are using a `.forEach`, for large data `array`, I prefer you use `.map` or old fashion `for loop`.

- [ ] You could also include your `dev` folder to ghpages and add the link to the `./dist` folder, this will enable access to your site instead of the readme file.

Cheers and happy coding 🐱‍🏍.
<img src="https://media3.giphy.com/media/1GEATImIxEXVR79Dhk/giphy.gif"/>

**Comment by daudi13** [comment]
Thanks for the feedback
